set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/plugins

set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @plugin 'tmux-plugins/tpm'

# Kanagawa options
set -g @kanagawa-plugins "battery time"
set -g @kanagawa-military-time true
set -g @kanagawa-time-format "%H:%M"
set -g @kanagawa-status-bg default
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-left-icon "#{?client_prefix,◉,○} #S"
set -g @kanagawa-left-icon-margin-right 0
set -g @kanagawa-time-colors "white default"
set -g @kanagawa-battery-colors "pink default"
set -g @kanagawa-show-battery-status true

# Basic settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g mouse on
set -g history-limit 30000
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -s escape-time 0
set -g prefix C-a
bind C-a send-prefix
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded"
set -g status-justify left

# Open new panes in current path
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

# Automatic window renaming
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

run '~/.tmux/plugins/tpm/tpm'

